#!/bin/bash
# Start UnoPim MCP Server (HTTP Mode)

cd /home/odm/projects/unoMcp

UNOPIM_BASE_URL='http://REDACTED-IP:8000' \
UNOPIM_CLIENT_ID='REDACTED-CLIENT-ID' \
UNOPIM_CLIENT_SECRET='REDACTED-SECRET' \
UNOPIM_USERNAME='REDACTED-EMAIL' \
UNOPIM_PASSWORD='REDACTED-PASSWORD' \
UNOPIM_DEFAULT_LOCALE='da_DK' \
UNOPIM_DEFAULT_CURRENCY='DKK' \
PORT='3000' \
node dist/index-http.js
